name: nitrogen6x-kernel
version: 4.9
summary: A Nitrogen6X kernel built from source
description: This provides a kernel snap for Boundary Device Nitrogen6X board
type: kernel
architectures: [armhf]
confinement: strict

parts:
  kernel:
    plugin: kernel
    source: https://github.com/boundarydevices/linux-imx6.git
    source-branch: boundary-imx_4.9.x_1.0.0_ga
    source-type: git
    override-build: |
            export ARCH=arm
            export CROSS_COMPILE=arm-linux-gnueabihf-
            make boundary_defconfig
            make zImage dtbs modules -j`cat /proc/cpuinfo |grep -c cpu`
    kdefconfig: [boundary_defconfig]
    kconfigs:
      - CONFIG_LOCALVERSION="-nitrogen6x"
      - CONFIG_DEBUG_INFO=n
      - CONFIG_EXT4_FS=y
      - CONFIG_BLK_DEV_LOOP=y
      - CONFIG_BLK_DEV_LOOP_MIN_COUNT=256
      - CONFIG_SQUASHFS=m
    kernel-initrd-modules:
      - squashfs
    kernel-image-target: Image
    build-packages: [debootstrap, lsb-release, crossbuild-essential-armhf]
